FlightsManager/Controllers/FlightController.cs
using FlightsManager.Models.Data;
using FlightsManager.Models.Web.Flights;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FlightsManager.Controllers
{
    public class FlightController : Controller
    {
        private const int PageSize = 10;
        private readonly FlightsManagerContext _context;
        public List<Tuple<int, List<string>>> passagerNames = new List<Tuple<int, List<string>>>();

        public FlightController()
        {
            _context = new FlightsManagerContext();
        }

        public async Task<IActionResult> AdminIndex(IndexFlightViewModel model)
        {
            model.Pager = new PagerViewModel();
            model.Pager.CurrentPage = model.Pager.CurrentPage <= 0 ? 1 : model.Pager.CurrentPage;

            List<FlightViewModel> items = await _context.Flights.Skip((model.Pager.CurrentPage - 1) * PageSize).Take(PageSize).Select(c => new FlightViewModel()
            {
                Id = c.Id,
                LocationFromId = c.LocationFromId,
                LocationToId = c.LocationToId,
                TakeOffDateTime = c.TakeOffDateTime,
                LandingDateTime = c.LandingDateTime,
                PlaneId = c.PlaneId

            }).ToListAsync();

            model.Items = items;
            model.Pager.PagesCount = (int)Math.Ceiling(_context.Flights.Count() / (double)PageSize);

            //////////////////// check for logged in employee -> admin
            byte[] empIdBytes = new byte[200];
            if (HttpContext.Session.TryGetValue("empId", out empIdBytes))
            {
                int employeeId = int.Parse(Encoding.UTF8.GetString(empIdBytes));
                if (employeeId == 1)
                {
                    List<Employee> employees = await (from emp in _context.Employees where 
                                                      emp.Id == employeeId select emp).ToListAsync();
                    Employee employee = employees[0];
                    ViewData["username"] = employee.Username;
                    ViewData["isLoggedIn"] = true;
                    ViewData["isAdmin"] = true;

                    return View(model);
                }
                else if(employeeId != 1 && employeeId > 0)
                {
                    List<Employee> employees = await (from emp in _context.Employees 
                                                      where emp.Id == employeeId select emp).ToListAsync();
                    Employee employee = employees[0];
                    ViewData["username"] = employee.Username;
                    ViewData["isLoggedIn"] = true;
                    ViewData["isAdmin"] = false;

                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewData["isLoggedIn"] = false;
                    ViewData["isAdmin"] = false;

                    return RedirectToAction(nameof(Index));
                }
            }
            else
            {
                ViewData["isLoggedIn"] = false;
                ViewData["isAdmin"] = false;

                return RedirectToAction(nameof(Index));
            }
            ///////////////////////////////////////////////////////////////
        }

        public async Task<IActionResult> Index(IndexFlightViewModel model)
        {
            model.Pager = new PagerViewModel();
            model.Pager.CurrentPage = model.Pager.CurrentPage <= 0 ? 1 : model.Pager.CurrentPage;

            List<FlightViewModel> items = await _context.Flights.Skip((model.Pager.CurrentPage - 1) * PageSize).Take(PageSize).Select(c => new FlightViewModel()
            {
                Id = c.Id,
                LocationFromId = c.LocationFromId,
                LocationToId = c.LocationToId,
                TakeOffDateTime = c.TakeOffDateTime,
                LandingDateTime = c.LandingDateTime,
                PlaneId = c.PlaneId

            }).ToListAsync();

            model.Items = items;
            model.Pager.PagesCount = (int)Math.Ceiling(_context.Flights.Count() / (double)PageSize);

            //////////////////// check for logged in employee -> admin 
            byte[] empIdBytes = new byte[200];
            if (HttpContext.Session.TryGetValue("empId", out empIdBytes))
            {
                int employeeId = int.Parse(Encoding.UTF8.GetString(empIdBytes));
                if (employeeId == 1)
                {
                    Employee employee = _context.Employees.Find(employeeId);
                    ViewData["username"] = employee.Username;
                    ViewData["isLoggedIn"] = true;
                    ViewData["isAdmin"] = true;

                    return RedirectToAction(nameof(AdminIndex));
                }
                else if (employeeId != 1 && employeeId > 0)
                {
                    Employee employee = _context.Employees.Find(employeeId); ;
                    ViewData["username"] = employee.Username;
                    ViewData["isLoggedIn"] = true;
                    ViewData["isAdmin"] = false;

                    return View(model);
                }
                else
                {
                    ViewData["isLoggedIn"] = false;
                    ViewData["isAdmin"] = false;

                    return View(model);
                }
            }
            else
            {
                ViewData["isLoggedIn"] = false;
                ViewData["isAdmin"] = false;

                return View(model);
            }
            ///////////////////////////////////////////////////////////////
        }

        public IActionResult Create()
        {
            byte[] empIdBytes = new byte[200];
            if (HttpContext.Session.TryGetValue("empId", out empIdBytes))
            {
                int employeeId = int.Parse(Encoding.UTF8.GetString(empIdBytes));
                if (employeeId == 1)
                {
                    List<Employee> employees = (from emp in _context.Employees
                                                     where
                      emp.Id == employeeId
                                                     select emp).ToList();
                    Employee employee = employees[0];
                    ViewData["username"] = employee.Username;
                    ViewData["isLoggedIn"] = true;
                    ViewData["isAdmin"] = true;

                    AddFlightViewModel model = new AddFlightViewModel();

                    List<Plane> planes = (from p in _context.Planes select p).ToList();
                    ViewData["allPlanes"] = planes;

                    return View(model);
                }
                else if (employeeId != 1 && employeeId > 0)
                {
                    List<Employee> employees = (from emp in _context.Employees
                                                     where emp.Id == employeeId
                                                     select emp).ToList();
                    Employee employee = employees[0];
                    ViewData["username"] = employee.Username;
                    ViewData["isLoggedIn"] = true;
                    ViewData["isAdmin"] = false;

                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewData["isLoggedIn"] = false;
                    ViewData["isAdmin"] = false;

                    return RedirectToAction(nameof(Index));
                }
            }
            else
            {
                ViewData["isLoggedIn"] = false;
                ViewData["isAdmin"] = false;

                return RedirectToAction(nameof(Index));
            }            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddFlightViewModel model)
        {
            byte[] empIdBytes = new byte[200];
            if (HttpContext.Session.TryGetValue("empId", out empIdBytes))
            {
                int employeeId = int.Parse(Encoding.UTF8.GetString(empIdBytes));
                if (employeeId == 1)
                {
                    List<Employee> employees = (from emp in _context.Employees
                                                where
                 emp.Id == employeeId
                                                select emp).ToList();
                    Employee employee = employees[0];
                    ViewData["username"] = employee.Username;
                    ViewData["isLoggedIn"] = true;
                    ViewData["isAdmin"] = true;

                    if (ModelState.IsValid)
                    {
                        int id = _context.Flights.Max(f => f.Id);
                        Flight flight = new Flight
                        {
                            Id = id + 1,
                            LocationFromId = model.LocationFromId,
                            LocationToId = model.LocationToId,
                            TakeOffDateTime = model.TakeOffDateTime,
                            LandingDateTime = model.LandingDateTime,
                            PlaneId = model.PlaneId
                        };

                        _context.Flights.Add(flight);
                        await _context.SaveChangesAsync();

                        passagerNames.Add(new Tuple<int, List<string>>(flight.Id, new List<string>()));

                        return RedirectToAction(nameof(Index));
                    }

                    return View(model);
                }
                else if (employeeId != 1 && employeeId > 0)
                {
                    List<Employee> employees = (from emp in _context.Employees
                                                where emp.Id == employeeId

FlightsManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Flights Manager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <script src="~/js/site.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Welcome">Flights Manager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="Index">Reservations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Flight" asp-action="Index">Flights</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="LoginForm">Administer</a>
                        </li>
                        <!--<li id="logOutBtn"style="display:block;">
                            <a asp-controller="Employee" asp-action="Logout">Log Out</a>
                        </li>-->
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Flights Manager - Contact us: petya.licheva2002@gmail.com
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>