FlightsManager/Models/Data/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace FlightsManager.Models.Data
{
    public partial class Employee
    {
        public Employee()
        {
            Planes = new HashSet<Plane>();
        }

        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Egn { get; set; }
        public int AddressId { get; set; }
        public string PhoneNumber { get; set; }
        public int RoleId { get; set; }

        public virtual EmployeeRole Role { get; set; }
        public virtual ICollection<Plane> Planes { get; set; }
    }
}

FlightsManager/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace FlightsManager.Models
{
    public partial class Employee
    {
        public Employee()
        {
            Planes = new HashSet<Plane>();
        }

        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(20)]
        public string Username { get; set; }

        [Required]
        [RegularExpression("^((?=.*?[A - Z])(?=.*?[a - z])(?=.*?[0 - 9]) | (?=.*?[A - Z])(?=.*?[a - z])(?=.*?[^a - zA - Z0 - 9]) | (?=.*?[A - Z])(?=.*?[0 - 9])(?=.*?[^a - zA - Z0 - 9]) | (?=.*?[a - z])(?=.*?[0 - 9])(?=.*?[^a - zA - Z0 - 9])).{8,}$")]
        public string Password { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Egn { get; set; }
        public int AddressId { get; set; }
        public string PhoneNumber { get; set; }
        public int RoleId { get; set; }

        public virtual EmployeeRole Role { get; set; }
        public virtual ICollection<Plane> Planes { get; set; }
    }
}

FlightsManager/Models/Web/Employees/EmployeeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FlightsManager.Models.Web.Employees
{
    public class EmployeeViewModel
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Egn { get; set; }
        public int AddressId { get; set; }
        public string PhoneNumber { get; set; }
        public int RoleId { get; set; }
    }
}

FlightsManager/Models/Web/Employees/IndexEmployeeViewModel.cs
using FlightsManager.Models.Web.Flights;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FlightsManager.Models.Web.Employees
{
    public class IndexEmployeeViewModel
    {
        public PagerViewModel Pager { get; set; }
        public List<EmployeeViewModel> Items { get; set; }
    }
}

FlightsManager/Models/Web/Employees/LoginEmployeeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FlightsManager.Models.Web.Employees
{
    public class LoginEmployeeViewModel
    {
        [Required]
        [StringLength(20)]
        public string Username { get; set; }

        [Required]
        [MinLength(8), MaxLength(20)]
        [RegularExpression("^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,20}$")]
        public string Password { get; set; }

        /*[Display(Name = "Remember me")]
        public bool RememberMe { get; set; }*/
    }
}

FlightsManager/Models/Web/Employees/SignUpEmployeeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FlightsManager.Models.Web.Employees
{
    public class SignUpEmployeeViewModel
    {
        [Required]
        [RegularExpression("[a-z]{3,}[0-9]{1,}")]
        public string Username { get; set; }
        [Required]
        [RegularExpression("^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,20}$")]
        public string Password { get; set; }
        [Required]
        [RegularExpression("^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,20}$")]
        [Compare(nameof(Password))]
        public string ReEnteredPassword { get; set; }
        [Required]
        [RegularExpression("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")]
        public string Email { get; set; }
        [Required]
        [RegularExpression("[A-Z]{1}[a-z]{1,}")]
        public string Name { get; set; }
        [Required]
        [RegularExpression("[A-Z]{1}[a-z]{1,}")]
        public string Family { get; set; }
        [Required]
        [RegularExpression("[0-9]{10}")]
        public string Egn { get; set; }
        [Required]
        [RegularExpression("[0-9]{1,}")]
        public int ContinentId { get; set; }
        [Required]
        [RegularExpression("[A-Z]{1}[a-z]{1,}")]
        public string Country { get; set; }
        [Required]
        [RegularExpression("[A-Z]{1}[a-z]{1,}")]
        public string LivingArea { get; set; }
        [Required]
        [RegularExpression("[A-Z]{1}[a-z]{1,}")]
        public string DestrictedArea { get; set; }
        [Required]
        [RegularExpression("[A-Z]{1}[a-z]{1,}")]
        public string Street { get; set; }
        [Required]
        [RegularExpression("[0-9]{1,}")]
        public int Number { get; set; }
        [Required]
        [RegularExpression("[0-9]{1,}")]
        public int Floor { get; set; }
        [Required]
        [RegularExpression("[0-9]{1,}")]
        public int Apartament { get; set; }
        [Required]
        [RegularExpression("((\\+359)|0)[0-9]{9}")]
        public string PhoneNumber { get; set; }
        [Required]
        [RegularExpression("[0-9]{1,}")]
        public int RoleId { get; set; }
    }
}

FlightsManager/Controllers/EmployeeController.cs
using FlightsManager.Models.Data;
using FlightsManager.Models.Web.Employees;
using FlightsManager.Utils;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FlightsManager.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly FlightsManagerContext _context;

        public EmployeeController()
        {
            _context = new FlightsManagerContext();
        }

        public IActionResult SignUpForm()
        {
            SignUpEmployeeViewModel model = new SignUpEmployeeViewModel();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignUp(SignUpEmployeeViewModel model)
        {
            Employee newEmployee = null;
            Country newCountry = null;
            LivingPlace newLivingPlace = null;
            DestrictedArea newDestrictedArea = null;
            Street newStreet = null;
            Address newAddress = null;
            CountryLivingPlace newCountryLivingPlace = null;
            LivingPlaceDestrictedArea newLivingPlaceDestrictedArea = null;
            DestrictedAreaStreet newDestrictedAreaStreet = null;

            if (ModelState.IsValid)
            {
                using (var _context = new FlightsManagerContext())
                {
                    int id = _context.Countries.Max(c => c.Id);
                    newCountry = new Country()
                    {
                        Id = id + 1,
                        Name = model.Country,
                        ContinentId = model.ContinentId
                    };
                    _context.Countries.Add(newCountry);
                    _context.SaveChanges();
                }
                using (var _context = new FlightsManagerContext())
                {
                    int id = _context.LivingPlaces.Max(l => l.Id);
                    newLivingPlace = new LivingPlace()
                    {
                        Id = id + 1,
                        Name = model.LivingArea
                    };
                    _context.LivingPlaces.Add(newLivingPlace);
                    _context.SaveChanges();
                }
                using (var _context = new FlightsManagerContext())
                {
                    int id = _context.DestrictedAreas.Max(d => d.Id);
                    newDestrictedArea = new DestrictedArea()
                    {
                        Id = id + 1,
                        Name = model.DestrictedArea
                    };
                    _context.DestrictedAreas.Add(newDestrictedArea);
                    _context.SaveChanges();
                }
                using (var _context = new FlightsManagerContext())
                {
                    int id = _context.Streets.Max(s => s.Id);
                    newStreet = new Street()
                    {
                        Id = id + 1,
                        Name = model.Street
                    };
                    _context.Streets.Add(newStreet);
                    _context.SaveChanges();
                }
                using (var _context = new FlightsManagerContext())
                {
                    int id = _context.Addresses.Max(a => a.Id);
                    newAddress = new Address()
                    {
                        Id = id + 1,
                        ContitnetId = model.ContinentId,
                        CountryId = newCountry.Id,
                        LivingPlaceId = newLivingPlace.Id,
                        DestrictedAreaId = newDestrictedArea.Id,
                        StreetId = newStreet.Id,
                        Number = model.Number,
                        Floor = model.Floor,
                        Apartament = model.Apartament,
                        AddressTypeId = 1
                    };
                    _context.Addresses.Add(newAddress);
                    _context.SaveChanges();
                }
                using (var _context = new FlightsManagerContext())
                {
                    int id = _context.CountryLivingPlaces.Max(e => e.Id);
                    newCountryLivingPlace = new CountryLivingPlace()
                    {
                        Id = id + 1,
                        CountryId = newCountry.Id,
                        LivingPlaceId = newLivingPlace.Id
                    };
                    _context.CountryLivingPlaces.Add(newCountryLivingPlace);
                    _context.SaveChanges();
                }
                using (var _context = new FlightsManagerContext())
                {
                    int id = _context.LivingPlaceDestrictedAreas.Max(e => e.Id);
                    newLivingPlaceDestrictedArea = new LivingPlaceDestrictedArea()
                    {
                        Id = id + 1,
                        LivingPlaceId = newLivingPlace.Id,
                        DestrictedAreaId = newDestrictedArea.Id
                    };
                    _context.LivingPlaceDestrictedAreas.Add(newLivingPlaceDestrictedArea);
                    _context.SaveChanges();
                }
                using (var _context = new FlightsManagerContext())
                {
                    int id = _context.DestrictedAreaStreets.Max(e => e.Id);
                    newDestrictedAreaStreet = new DestrictedAreaStreet()
                    {
                        Id = id + 1,
                        DestrictedAreaId = newDestrictedArea.Id,
                        StreetId = newStreet.Id
                    };
                    _context.DestrictedAreaStreets.Add(newDestrictedAreaStreet);
                    _context.SaveChanges();
                }
                using (var _context = new FlightsManagerContext())
                {
                    int id = _context.Employees.Max(e => e.Id);
                    newEmployee = new Employee()
                    {
                        Id = id + 1,
                        Username = model.Username,
                        Password = HashPassword.GenerateSHA512(model.Password),
                        Email = model.Email,
                        Name = model.Name,
                        Family = model.Family,
                        Egn = model.Egn,
                        AddressId = newAddress.Id,
                        PhoneNumber = model.PhoneNumber,
                        RoleId = 2
                    };
                    _context.Employees.Add(newEmployee);
                    await _context.SaveChangesAsync();
                }

                return RedirectToAction(nameof(LoginForm));
            }
            else
            {
                return View(model);
            }
        }

        public IActionResult LoginForm()
        {
            LoginEmployeeViewModel model = new LoginEmployeeViewModel();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginEmployeeViewModel model)
        {
            if (ModelState.IsValid)
            {
                string hashedPass = HashPassword.GenerateSHA512(model.Password);
                var query = from emp in _context.Employees where emp.Username == model.Username && emp.Password == hashedPass select emp;
                List<Employee> employees = await query.ToListAsync();
                if (employees != null && employees.Count != 0)
                {
                    Employee employee = employees[0];

                    if (employee != null)
                    {
                        HttpContext.Session.Set("empId", Encoding.UTF8.GetBytes(employee.Id.ToString()));
                        if (employee.Id == 1)
                        {
                            ViewData["username"] = employee.Username;
                            return RedirectToAction("AdminIndex", "Flight");
                        }
                        else if (employee.Id != 1 && employee.Id > 0)
                        {
                            ViewData["username"] = employee.Username;
                            return RedirectToAction("Index", "Flight");
                        }
                        else
                        {
                            ViewData["incorrectCredentials"] = "Your credentials were incorrect! Please, type correct username and password!";
                            return RedirectToAction(nameof(LoginForm));
                        }
                    }
                    else
                    {
                        ViewData["incorrectCredentials"] = "Your credentials were incorrect! Please, type correct username and password!";
                        return RedirectToAction(nameof(LoginForm));
                    }
                }
                else
                {
                    ViewData["incorrectCredentials"] = "Your credentials were incorrect! Please, type correct username and password!";
                    return RedirectToAction(nameof(LoginForm));
                }
            }
            else
            {
                ViewData["incorrectCredentials"] = "Your credentials were incorrect! Please, type correct username and password!";
                return RedirectToAction(nameof(LoginForm));
            }
        }
 
        public IActionResult LogOut()
        {
            int empId = -1;
            HttpContext.Session.Set("empId", Encoding.UTF8.GetBytes(empId.ToString()));
            return RedirectToAction(nameof(LoginForm));
        } 
    }
}

FlightsManager/Views/Employee/LoginForm.cshtml
@model FlightsManager.Models.Web.Employees.LoginEmployeeViewModel
@{
    ViewData["Title"] = "Login";
    string incorrectLoginMsg = ViewData["incorrectCredentials"] as string;
}
<h1 class="text-left text-info title">@ViewData["Title"]</h1>
@{ 
    if (incorrectLoginMsg != null && incorrectLoginMsg != "" && incorrectLoginMsg.Length > 0)
    {
        <p>@incorrectLoginMsg</p>
    }
}
<form method="post" asp-action="Login" class="container container-fluid form">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <input asp-for="Username" class="form-control required-fields" placeholder="Username" type="text" />
        <span class="text-danger required-fields-symbol">*</span><br />
        <span asp-validation-for="Username" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input asp-for="Password" class="form-control required-fields" placeholder="Password" type="password" />
        <span class="text-danger required-fields-symbol">*</span><br />
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Login" class="btn btn-primary" />
        <a type="button" name="signUpBtn" class="btn btn-light" asp-area="" asp-controller="Employee" asp-action="SignUpForm">Sign Up</a>
    </div>
</form>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FlightsManager/Views/Employee/SignUpForm.cshtml
@model FlightsManager.Models.Web.Employees.SignUpEmployeeViewModel
@{
    ViewData["Title"] = "Sign Up";
}
<h1 class="text-left text-info title">@ViewData["Title"]</h1>

<form method="post" asp-action="SignUp" class="container container-fluid form">
    <table>
        <thead>
            <tr class="row">
                <th class="col-md-4">
                    Personal Information
                </th>
                <th class="col-md-4">
                    Address
                </th>
                <th class="col-md-4">
                    Profile Information
                </th>
            </tr>
        </thead>
        <tbody>
            <tr class="row">
                <td class="col-md-4">
                    <input asp-for="Name" type="text" class="form-control required-fields" placeholder="Name" />
                    <span class="text-danger required-fields-symbol">*</span><br />
                    <span asp-validation-for="Name" class="text-danger"></span>

                    <input asp-for="Family" type="text" class="form-control required-fields" placeholder="Family" />
                    <span class="text-danger required-fields-symbol">*</span><br />
                    <span asp-validation-for="Family" class="text-danger"></span>

                    <input asp-for="Egn" type="text" class="form-control required-fields" placeholder="Personal Identification Number" />
                    <span class="text-danger required-fields-symbol">*</span><br />
                    <span asp-validation-for="Egn" class="text-danger"></span>

                    <input asp-for="PhoneNumber" type="text" class="form-control required-fields" placeholder="Phone Number" />
                    <span class="text-danger required-fields-symbol">*</span><br />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>

                    <input asp-for="Email" type="text" class="form-control required-fields" placeholder="Email" />
                    <span class="text-danger required-fields-symbol">*</span><br />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </td>
                <td class="col-md-4">
                    <select asp-for="ContinentId" class="form-control required-fields">
                        <option value="1">Antarctida</option>
                        <option value="2">Asia</option>
                        <option value="3">Africa</option>
                        <option value="4">Australia</option>
                        <option value="5">Europe</option>
                        <option value="6">North America</option>
                        <option value="7">South America</option>
                    </select>
                    <span class="text-danger required-fields-symbol">*</span><br />
                    <span asp-validation-for="ContinentId" class="text-danger"></span>

                    <input asp-for="Country" type="text" class="form-control required-fields" placeholder="Country" />
                    <span class="text-danger required-fields-symbol">*</span><br />
                    <span asp-validation-for="Country" class="text-danger"></span>

                    <input asp-for="LivingArea" type="text" class="form-control required-fields" placeholder="Living Area" />
                    <span class="text-danger required-fields-symbol">*</span><br />
                    <span asp-validation-for="LivingArea" class="text-danger"></span>

                    <input asp-for="DestrictedArea" type="text" class="form-control required-fields" placeholder="Destricted Area" />
                    <span class="text-danger required-fields-symbol">*</span><br />
                    <span asp-validation-for="DestrictedArea" class="text-danger"></span>

                    <input asp-for="Street" type="text" class="form-control required-fields" placeholder="Street" />
                    <span class="text-danger required-fields-symbol">*</span><br />
                    <span asp-validation-for="Street" class="text-danger"></span>

                    <input asp-for="Number" type="text" class="form-control required-fields" placeholder="Number" />
                    <span class="text-danger required-fields-symbol">*</span><br />
                    <span asp-validation-for="Number" class="text-danger"></span>

                    <input asp-for="Floor" type="text" class="form-control required-fields" placeholder="Floor" />
                    <br />
                    <span asp-validation-for="Floor" class="text-danger"></span>

                    <input asp-for="Apartament" type="text" class="form-control required-fields" placeholder="Apartament" />
                    <br />
                    <span asp-validation-for="Apartament" class="text-danger"></span>
                </td>
                <td class="col-md-4">
                    <input asp-for="Username" type="text" class="form-control required-fields" placeholder="Username" />
                    <span class="text-danger required-fields-symbol">*</span><br />
                    <span asp-validation-for="Username" class="text-danger"></span>

                    <input asp-for="Password" type="password" class="form-control required-fields" placeholder="Password" />
                    <span class="text-danger required-fields-symbol">*</span><br />
                    <span asp-validation-for="Password" class="text-danger"></span>

                    <input asp-for="ReEnteredPassword" type="password" class="form-control required-fields" placeholder="Re-Enter Password" />
                    <span class="text-danger required-fields-symbol">*</span><br />
                    <span asp-validation-for="ReEnteredPassword" class="text-danger"></span>

                    <select asp-for="RoleId" class="form-control required-fields">
                        <option value="1">Employee</option>
                    </select>
                    <span class="text-danger required-fields-symbol">*</span><br />
                    <span asp-validation-for="RoleId" class="text-danger"></span>
                </td>
            </tr>
            <tr class="row">
                <td class="col-md-12">
                    <input type="submit" value="Sign Up" class="btn btn-primary" />
                    <a type="button" class="btn btn-light" name="signUpBtn" asp-area="" asp-controller="Employee" asp-action="LoginForm">Login</a>
                </td>
            </tr>
        </tbody>
    </table>
</form>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}