FlightsManager/Models/Data/Reservation.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace FlightsManager.Models.Data
{
    public partial class Reservation
    {
        public Reservation()
        {
            ReservationPassagers = new HashSet<ReservationPassager>();
            ReservationConfirmations = new HashSet<Reservation_Confirmation>();
        }

        public int Id { get; set; }
        public DateTime ReservationDate { get; set; }
        public int TicketId { get; set; }

        public virtual Ticket Ticket { get; set; }
        public virtual ICollection<ReservationPassager> ReservationPassagers { get; set; }
        public virtual ICollection<Reservation_Confirmation> ReservationConfirmations { get; set; }
    }
}

FlightsManager/Models/Web/Reservation/AddReservationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FlightsManager.Models.Web.Reservation
{
    public class AddReservationViewModel
    {
        [Required]
        [RegularExpression("[0-9]{1,}")]
        public int Id { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        public DateTime ReservationDate { get; set; }
        [Required]
        [RegularExpression("[0-9]{1,}")]
        public int FlightId { get; set; }
        [Required]
        [RegularExpression("[A-Z]{1}[a-z]{1,}")]
        public string FirstName { get; set; }
        [Required]
        [RegularExpression("[A-Z]{1}[a-z]{1,}")]
        public string SecondName { get; set; }
        [Required]
        [RegularExpression("[A-Z]{1}[a-z]{1,}")]
        public string LastName { get; set; }
        [Required]
        [RegularExpression("[0-9]{10}")]
        public string EGN { get; set; }
        [Required]
        [RegularExpression("[0-9]{1,}")]
        public int NationalityId { get; set; }
        [Required]
        [RegularExpression("((\\+359)|0)[0-9]{9}")]
        public string PhoneNumber { get; set; }
        [Required]
        [RegularExpression("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")]
        public string Email { get; set; }
        [Required]
        [RegularExpression("[0-9]{1,}")]
        public int TicketTypeId { get; set; }
    }
}

FlightsManager/Models/Web/Reservation/IndexReservationViewModel.cs
using FlightsManager.Models.Web.Flights;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FlightsManager.Models.Web.Reservation
{
    public class IndexReservationViewModel
    {
        public PagerViewModel Pager { get; set; }
        public List<ReservationViewModel> Items { get; set; }
    }
}

FlightsManager/Models/Web/Reservation/ReservationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FlightsManager.Models.Web.Reservation
{
    public class ReservationViewModel
    {
        public int Id { get; set; }
        public DateTime ReservationDate { get; set; }
        public int TicketId { get; set; }
    }
}

FlightsManager/Controllers/ReservationController.cs
using FlightsManager.Models.Data;
using FlightsManager.Models.Web.Reservation;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting.Internal;
using MimeKit;
using System;
using MailKit.Net.Smtp;
using System.Collections.Generic;
using System.Linq;
//using System.Net.Mail;
using System.Threading.Tasks;
using System.Text;
using Microsoft.EntityFrameworkCore;
using FlightsManager.Models.Web.Flights;
using System.Net.Mail;
using System.Net;

namespace FlightsManager.Controllers
{
    public class ReservationController : Controller
    {
        private const int PageSize = 10;
        private readonly FlightsManagerContext _context;
        private FlightController flightCtrl = new FlightController();

        public ReservationController() 
        {
            _context = new FlightsManagerContext();
        }

        public async Task<IActionResult> AdminIndex(IndexReservationViewModel model)
        {
            model.Pager = new PagerViewModel();
            model.Pager.CurrentPage = model.Pager.CurrentPage <= 0 ? 1 : model.Pager.CurrentPage;

            List<ReservationViewModel> items = await _context.Reservations.Skip((model.Pager.CurrentPage - 1) * PageSize).Take(PageSize).Select(c => new ReservationViewModel()
            {
                Id = c.Id,
                ReservationDate = c.ReservationDate,
                TicketId = c.TicketId

            }).ToListAsync();

            model.Items = items;
            model.Pager.PagesCount = (int)Math.Ceiling(_context.Reservations.Count() / (double)PageSize);

            //////////////////// check for logged in employee -> admin
            byte[] empIdBytes = new byte[200];
            if (HttpContext.Session.TryGetValue("empId", out empIdBytes))
            {
                int employeeId = int.Parse(Encoding.UTF8.GetString(empIdBytes));
                if (employeeId == 1)
                {
                    List<Employee> employees = await (from emp in _context.Employees
                                                      where
                       emp.Id == employeeId
                                                      select emp).ToListAsync();
                    Employee employee = employees[0];
                    ViewData["username"] = employee.Username;
                    ViewData["isLoggedIn"] = true;
                    ViewData["isAdmin"] = true;

                    return View(model);
                }
                else if (employeeId != 1 && employeeId > 0)
                {
                    List<Employee> employees = await (from emp in _context.Employees
                                                      where emp.Id == employeeId
                                                      select emp).ToListAsync();
                    Employee employee = employees[0];
                    ViewData["username"] = employee.Username;
                    ViewData["isLoggedIn"] = true;
                    ViewData["isAdmin"] = false;

                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewData["isLoggedIn"] = false;
                    ViewData["isAdmin"] = false;

                    return RedirectToAction(nameof(Index));
                }
            }
            else
            {
                ViewData["isLoggedIn"] = false;
                ViewData["isAdmin"] = false;

                return RedirectToAction(nameof(Index));
            }
            ///////////////////////////////////////////////////////////////
        }
        public async Task<IActionResult> Index(IndexReservationViewModel model)
        {
            model.Pager = new PagerViewModel();
            model.Pager.CurrentPage = model.Pager.CurrentPage <= 0 ? 1 : model.Pager.CurrentPage;

            List<ReservationViewModel> items = await _context.Reservations.Skip((model.Pager.CurrentPage - 1) * PageSize).Take(PageSize).Select(c => new ReservationViewModel()
            {
                Id = c.Id,
                ReservationDate = c.ReservationDate,
                TicketId = c.TicketId

            }).ToListAsync();

            model.Items = items;
            model.Pager.PagesCount = (int)Math.Ceiling(_context.Reservations.Count() / (double)PageSize);

            //////////////////// check for logged in employee -> admin
            byte[] empIdBytes = new byte[200];
            if (HttpContext.Session.TryGetValue("empId", out empIdBytes))
            {
                int employeeId = int.Parse(Encoding.UTF8.GetString(empIdBytes));
                if (employeeId == 1)
                {
                    List<Employee> employees = await (from emp in _context.Employees
                                                      where
                       emp.Id == employeeId
                                                      select emp).ToListAsync();
                    Employee employee = employees[0];
                    ViewData["username"] = employee.Username;
                    ViewData["isLoggedIn"] = true;
                    ViewData["isAdmin"] = true;

                    return RedirectToAction(nameof(AdminIndex));
                }
                else if (employeeId != 1 && employeeId > 0)
                {
                    List<Employee> employees = await (from emp in _context.Employees
                                                      where emp.Id == employeeId
                                                      select emp).ToListAsync();
                    Employee employee = employees[0];
                    ViewData["username"] = employee.Username;
                    ViewData["isLoggedIn"] = true;
                    ViewData["isAdmin"] = false;

                    return View(model);
                }
                else
                {
                    ViewData["isLoggedIn"] = false;
                    ViewData["isAdmin"] = false;

                    return View(model);
                }
            }
            else
            {
                ViewData["isLoggedIn"] = false;
                ViewData["isAdmin"] = false;

                return View(model);
            }
            ///////////////////////////////////////////////////////////////
        }

        public async Task<IActionResult> ReservationDateSortedAdminIndex(IndexReservationViewModel model) 
        {
            byte[] empIdBytes = new byte[200];
            if (HttpContext.Session.TryGetValue("empId", out empIdBytes))
            {
                int employeeId = int.Parse(Encoding.UTF8.GetString(empIdBytes));
                if (employeeId == 1)
                {
                    List<Employee> employees = await (from emp in _context.Employees
                                                      where
                       emp.Id == employeeId
                                                      select emp).ToListAsync();
                    Employee employee = employees[0];
                    ViewData["username"] = employee.Username;
                    ViewData["isLoggedIn"] = true;
                    ViewData["isAdmin"] = true;

                    model.Pager = new PagerViewModel();
                    model.Pager.CurrentPage = model.Pager.CurrentPage <= 0 ? 1 : model.Pager.CurrentPage;

                    List<ReservationViewModel> items = await _context.Reservations.Skip((model.Pager.CurrentPage - 1) * PageSize).Take(PageSize).Select(c => new ReservationViewModel()
                    {
                        Id = c.Id,
                        ReservationDate = c.ReservationDate,
                        TicketId = c.TicketId

                    }).OrderByDescending(it => it.ReservationDate).ToListAsync();
                    model.Items = items;

                    return View(model);
                }
                else if (employeeId != 1 && employeeId > 0)
                {
                    List<Employee> employees = await (from emp in _context.Employees
                                                      where emp.Id == employeeId
                                                      select emp).ToListAsync();
                    Employee employee = employees[0];
                    ViewData["username"] = employee.Username;
                    ViewData["isLoggedIn"] = true;
                    ViewData["isAdmin"] = false;

                    return RedirectToAction(nameof(ReservationDateSortedIndex));
                }
                else
                {
                    ViewData["isLoggedIn"] = false;
                    ViewData["isAdmin"] = false;

                    return RedirectToAction(nameof(ReservationDateSortedIndex));
                }
            }
            else
            {
                ViewData["isLoggedIn"] = false;
                ViewData["isAdmin"] = false;

                return RedirectToAction(nameof(ReservationDateSortedIndex));
            }
        }

        public async Task<IActionResult> ReservationDateSortedIndex (IndexReservationViewModel model) 
        {
            byte[] empIdBytes = new byte[200];
            if (HttpContext.Session.TryGetValue("empId", out empIdBytes))
            {
                int employeeId = int.Parse(Encoding.UTF8.GetString(empIdBytes));
                if (employeeId == 1)
                {
                    List<Employee> employees = await (from emp in _context.Employees
                                                      where
                       emp.Id == employeeId
                                                      select emp).ToListAsync();
                    Employee employee = employees[0];
                    ViewData["username"] = employee.Username;
                    ViewData["isLoggedIn"] = true;
                    ViewData["isAdmin"] = true;

                    return RedirectToAction(nameof(ReservationDateSortedAdminIndex));
                }

FlightsManager/Views/Reservation/AdminIndex.cshtml
@model FlightsManager.Models.Web.Reservation.IndexReservationViewModel
@{
    bool isLoggedIn = (bool)ViewData["isLoggedIn"];
    string unm = (string)ViewData["username"];
    if (isLoggedIn)
    {
        <p>Welcome, <strong style="color:darkred;">@unm</strong>!</p>
        <a type="button" class="btn btn-dark" asp-area="" asp-controller="Employee" asp-action="LogOut">LogOut</a>
        <a asp-controller="Reservation" class="btn btn-light" asp-action="ReservationDateSortedIndex">Sort By Reservation Date</a>
    }
    else
    {
        <a asp-controller="Reservation" class="btn btn-light" asp-action="ReservationDateSortedIndex">Sort By Reservation Date</a>
    }

    FlightsManager.Models.Data.FlightsManagerContext _context = new FlightsManager.Models.Data.FlightsManagerContext();
}

<hr />
<table class="table">
    <thead>
        <tr>
            <th>
                Reservation Date
            </th>
            <th>
                Location From
            </th>
            <th>
                Location To
            </th>
            <th>
                Passager Name
            </th>
            <th>
                Passager Family
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Items)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ReservationDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => _context.Countries.Find(_context.Addresses.Find(_context.Flights.Find(_context.Tickets.Find(item.TicketId).FlightId).LocationFromId).CountryId).Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => _context.Countries.Find(_context.Addresses.Find(_context.Flights.Find(_context.Tickets.Find(item.TicketId).FlightId).LocationToId).CountryId).Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => _context.Passagers.Find((from r in _context.ReservationPassagers where r.ResrvationId == item.Id select r).First().PassagerId).FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => _context.Passagers.Find((from r in _context.ReservationPassagers where r.ResrvationId == item.Id select r).First().PassagerId).LastName)
                </td>
                <td>
                    <a asp-controller="Reservation" asp-action="Details" asp-route-id="@item.Id">Details</a>
                </td>
                <td>
                    <a asp-controller="Reservation" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
    <ul class="pagination">
        @for (var i = 1; i <= Model.Pager.PagesCount; i++)
        {
            <li class="page-item @(i == Model.Pager.CurrentPage ? "active" : "")">
                <a asp-route-Pager.CurrentPage="@i" class="page-link">@i</a>
            </li>
        }
    </ul>
</table>

FlightsManager/Views/Reservation/Create.cshtml
@model FlightsManager.Models.Web.Reservation.AddReservationViewModel
@{
    ViewData["Title"] = "Login";

    bool isLoggedIn = (bool)ViewData["isLoggedIn"];
    string unm = (string)ViewData["username"];
    if (isLoggedIn)
    {
        <p>Welcome, <strong style="color:darkred;">@unm</strong>!</p>
        <a type="button" class="btn btn-dark" asp-area="" asp-controller="Employee" asp-action="LogOut">LogOut</a>
        <a asp-controller="Reservation" class="btn btn-light" asp-action="ReservationDateSortedIndex">Sort By Reservation Date</a>
    }
    else
    {
        <a asp-controller="Reservation" class="btn btn-light" asp-action="ReservationDateSortedIndex">Sort By Reservation Date</a>
    }

    FlightsManager.Models.Data.Flight resFlight = ViewData["resevationFlight"] as FlightsManager.Models.Data.Flight;

    FlightsManager.Models.Data.FlightsManagerContext ctx = new FlightsManager.Models.Data.FlightsManagerContext();
    string locFrom = ctx.LivingPlaces.Find(ctx.Addresses.Find(resFlight.LocationFromId).LivingPlaceId).Name + ", " + ctx.Countries.Find(ctx.Addresses.Find(resFlight.LocationFromId).CountryId).Name;
    string locTo = ctx.LivingPlaces.Find(ctx.Addresses.Find(resFlight.LocationToId).LivingPlaceId).Name + ", " + ctx.Countries.Find(ctx.Addresses.Find(resFlight.LocationToId).CountryId).Name;

    int reservationId = ctx.Reservations.Max(r => r.Id) + 1;
    string reservationDate = DateTime.Now.ToShortDateString();

    string upn = ctx.Planes.Find(resFlight.PlaneId).UniquePlaneNumber;
    string pilotFullName = ctx.Employees.Find(ctx.Planes.Find(resFlight.PlaneId).PilotId).Name + " " + ctx.Employees.Find(ctx.Planes.Find(resFlight.PlaneId).PilotId).Family;

    string takeOffDate = resFlight.TakeOffDateTime.ToShortDateString();
    string landingDate = resFlight.LandingDateTime.ToShortDateString();
    string duration = (resFlight.LandingDateTime - resFlight.TakeOffDateTime).TotalMinutes + " mins.";

    List<FlightsManager.Models.Data.Nationality> nationalities = (from n in ctx.Nationalities select n).ToList();
    List<FlightsManager.Models.Data.Ticket> ticketType = (from t in ctx.Tickets where t.FlightId == resFlight.Id select t).ToList();
    List<FlightsManager.Models.Data.TicketType> ticketTypeNames = new List<FlightsManager.Models.Data.TicketType>();
    for (int i = 0; i < ticketType.Count; i++)
    {
        FlightsManager.Models.Data.TicketType _tickNm = (from _t in ctx.TicketTypes where _t.Id == ticketType[i].TicketTypeId select _t).First();
        ticketTypeNames.Add(_tickNm);
    }
}

<hr />
<form method="post" asp-action="Create" class="container container-fluid form">
    <table class="table" id="resTbl">
        <thead>
            <tr class="d-table-row">
                <th class="table-active col-3">
                    <p>Reservation Number</p>
                </th>
                <td class="col-3">
                    <p asp-for="Id" type="text" class="form-control required-fields">@reservationId</p>
                </td>
                <th class="table-active col-3">
                    <p>Reservation Date</p>
                </th>
                <td class="col-3">
                    <p asp-for="ReservationDate" type="text" class="form-control required-fields">@reservationDate</p>
                </td>
            </tr>
        </thead>
        <tbody>
            <tr class="d-table-row">
                <th class="table-active col-2" rowspan="2">
                    <p>Flight</p>
                </th>
                <th class="table-active col-2">
                    <p>Location From</p>
                </th>
                <th class="table-active col-2">
                    <p>Location To</p>
                </th>
                <th class="table-active col-2">
                    <p>Take Off Date</p>
                </th>
                <th class="table-active col-2">
                    <p>Landing Date</p>
                </th>
                <th class="table-active col-2">
                    <p>Duration</p>
                </th>
            </tr>
            <tr class="d-table-row">
                <td class="col-2">
                    <p>
                        @locFrom
                    </p>
                </td>
                <td class="col-2">
                    <p>
                        @locTo
                    </p>
                </td>
                <td class="col-2">
                    <p>
                        @takeOffDate
                    </p>
                </td>
                <td class="col-2">
                    <p>
                        @landingDate
                    </p>
                </td>
                <td class="col-2">
                    <p>
                        @duration
                    </p>
                </td>
            </tr>
            <tr class="d-table-row">
                <th class="table-active col-3" rowspan="2">
                    <p>Plane</p>
                </th>
                <th class="table-active col-3">
                    <p>Plane Type</p>
                </th>
                <th class="table-active col-3">
                    <p>Unique Plane Number</p>
                </th>
                <th class="table-active col-3">
                    <p>Pilot Name</p>
                </th>
            </tr>
            <tr class="d-table-row">
                <td class="col-3">
                    <p>
                        Airliner
                    </p>
                </td>
                <td class="col-3">
                    <p>
                        @upn
                    </p>
                </td>
                <td class="col-3">
                    <p>
                        @pilotFullName
                    </p>
                </td>
            </tr>
            <tr class="d-table-row">
                <th class="table-active col-2" rowspan="2">
                    <p>Personal Information</p>
                </th>
                <th class="table-active col-2">
                    <p>First Name</p>
                </th>
                <th class="table-active col-2">
                    <p>Second Name</p>
                </th>
                <th class="table-active col-2">
                    <p>Last Name</p>
                </th>
                <th class="table-active col-2">
                    <p>PIN</p>
                </th>
                <th class="table-active col-2">
                    <p>Nationality</p>
                </th>
            </tr>
            <tr id="pInfRow" class="d-table-row">
                <td class="col-2">
                    <input asp-for="FirstName" class="form-control required-fields" type="text" placeholder="First Name" />
                    <span class="text-danger required-fields-symbol">*</span><br />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </td>
                <td class="col-2">
                    <input asp-for="SecondName" class="form-control required-fields" type="text" placeholder="Second Name" />
                    <span class="text-danger required-fields-symbol">*</span><br />
                    <span asp-validation-for="SecondName" class="text-danger"></span>
                </td>
                <td class="col-2">
                    <input asp-for="LastName" class="form-control required-fields" type="text" placeholder="Last Name" />
                    <span class="text-danger required-fields-symbol">*</span><br />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </td>
                <td class="col-2">
                    <input asp-for="EGN" class="form-control required-fields" type="text" placeholder="Personal Identification Number" />
                    <span class="text-danger required-fields-symbol">*</span><br />
                    <span asp-validation-for="EGN" class="text-danger"></span>
                </td>
                <td class="col-2" id="nat">
                    <select asp-for="NationalityId" class="form-control required-fields">
                        @{
                            for (int i = 0; i < nationalities.Count; i++)
                            {
                                <option value=@nationalities[i].Id>@nationalities[i].Name</option>
                            }
                        }
                    </select>
                    <span class="text-danger required-fields-symbol">*</span><br />
                    <span asp-validation-for="NationalityId" class="text-danger"></span>
                </td>
            </tr>
            <tr class="d-table-row">
                <th class="table-active col-4" rowspan="2">
                    <p>Feedback</p>
                </th>
                <th class="table-active col-4">
                    <p>PhoneNumber</p>
                </th>
                <th class="table-active col-4">
                    <p>Email</p>
                </th>
            </tr>
            <tr class="d-table-row">
                <td class="col-4">
                    <input asp-for="PhoneNumber" class="form-control required-fields" type="text" placeholder="Phone Number" />
                    <span class="text-danger required-fields-symbol">*</span><br />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </td>
                <td class="col-4">
                    <input asp-for="Email" class="form-control required-fields" type="text" placeholder="Email" />
                    <span class="text-danger required-fields-symbol">*</span><br />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </td>
            </tr>
            <tr class="d-table-row">
                <th class="table-active col-12">
                    <p>Tickets</p>
                </th>
            </tr>
            <tr class="d-table-row">
                <th class="table-active col-3">
                    <p>Ticket Type</p>
                </th>
                <th class="table-active col-3">
                    <p>Ticket Count</p>
                </th>
                <th class="table-active col-3">
                    <p>Total Price</p>
                </th>
            </tr>
            <tr class="d-table-row">
                <td class="col-3">
                    <select asp-for="TicketTypeId">
                        @{
                            for (int j = 0; j < ticketTypeNames.Count; j++)
                            {

                                <option value=@ticketTypeNames[j].Id>@ticketTypeNames[j].Name</option>
                            }
                        }
                    </select>
                </td>
                <td class="col-3">
                    <p>1</p>
                </td>
                <td class="col-3">
                    <p>-</p>
                </td>
            </tr>
            <tr class="d-table-row">
                <td class="col-6">
                    <a href="/Flight/Index" class="btn btn-light">Cancel</a>
                </td>
                <td class="col-6">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </td>
            </tr>
        </tbody>
    </table>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FlightsManager/Views/Reservation/Index.cshtml
@model FlightsManager.Models.Web.Reservation.IndexReservationViewModel
@{
    bool isLoggedIn = (bool)ViewData["isLoggedIn"];
    string unm = (string)ViewData["username"];
    if (isLoggedIn)
    {
        <p>Welcome, <strong style="color:darkred;">@unm</strong>!</p>
        <a type="button" class="btn btn-dark" asp-area="" asp-controller="Employee" asp-action="LogOut">LogOut</a>
        <a asp-controller="Reservation" class="btn btn-light" asp-action="ReservationDateSortedIndex">Sort By Reservation Date</a>
    }
    else
    {
        <a asp-controller="Reservation" class="btn btn-light" asp-action="ReservationDateSortedIndex">Sort By Reservation Date</a>
    }

    FlightsManager.Models.Data.FlightsManagerContext _context = new FlightsManager.Models.Data.FlightsManagerContext();
}

<hr />
<table class="table">
    <thead>
        <tr>
            <th>
                Reservation Date
            </th>
            <th>
                Location From
            </th>
            <th>
                Location To
            </th>
            <th>
                Passager Name
            </th>
            <th>
                Passager Family
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Items)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ReservationDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => _context.Countries.Find(_context.Addresses.Find(_context.Flights.Find(_context.Tickets.Find(item.TicketId).FlightId).LocationFromId).CountryId).Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => _context.Countries.Find(_context.Addresses.Find(_context.Flights.Find(_context.Tickets.Find(item.TicketId).FlightId).LocationToId).CountryId).Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => _context.Passagers.Find((from r in _context.ReservationPassagers where r.ResrvationId == item.Id select r).First().PassagerId).FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => _context.Passagers.Find((from r in _context.ReservationPassagers where r.ResrvationId == item.Id select r).First().PassagerId).LastName)
                </td>
            </tr>
        }
    </tbody>
    <ul class="pagination">
        @for (var i = 1; i <= Model.Pager.PagesCount; i++)
        {
            <li class="page-item @(i == Model.Pager.CurrentPage ? "active" : "")">
                <a asp-route-Pager.CurrentPage="@i" class="page-link">@i</a>
            </li>
        }
    </ul>
</table>